// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "ca055a9e995be185a445b2395d32c380"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"7e42fa8ce2b2281fe45f247698df476a": "1f8b08000000000000ff8c534f4fc23014bff753bc234439e8c984d3848a8ddbc4b219392d736d48136967d769f8f6667f0aeb28c47722e5f7defbfd799bcde0662f763a371cd212a142f3e6a7c93fbf38147565d49eeb0a4d10008060b0c1940421ac298902ba8517bc45d3f9b84dd5d268c1076d833a9f70dba234cf59d39ec97ccf21c11f09c4af09c46918421a93b7149f6fda29c57c5b2eed2814e316f31ed0c573402777f70fd3f1a60ecd785568511aa164c7c7964577b0528bc24e5de2058982d0859df316f24789e28241c77a24ab8b42fa6432b795c4095e610a143f618ae305de9c32848960d31175c62b2364de28ccbad40ecd44df189ba96f4c2f27638dc2532524c29b2488d65e75ff72282b736d3c365db1a6b989de161227430dedb574fc7d39d65298ac0bd389f10aefaef1bbcea511e6d06fbc567edf046b048dd8da1b710d6f9d1a7eb44bf52b11625a953ee7e69e7fdcc7d614e7e518b5fb6aef688efe020000ffff2ee2384834040000",
		"f7d693da68cada5ea3ba8ab9b7f7f7a9": "1f8b08000000000000ff74ccbb0dc2400c06e0de53fc5d40280d123469598101cc9d79483e3b727cb03eed3559e09b679cdae7159c82fb4ac49a12487ea8a0f42dbd496ce05a515c7b331837c197a3bc390ee7cbf508f3847555547972d7c4342d44237cf39fedd1357c1ded85fe010000ffff51882d1f93000000",
		"fae9fb06ac5b01da0ffb2aff58b7a578": "1f8b08000000000000ffd2d555d0cecd4c2f4a2c4955082de0e24a2e4a0531532b4a52f38a33f3f3140ad2e34b8ad273adb9b89095bae497e77171a514e51760530a080000fffff7015c2055000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("migrations", "./migrations")
		b.SetResolver("001_schema_init.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "7e42fa8ce2b2281fe45f247698df476a"})
		b.SetResolver("002_names.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "f7d693da68cada5ea3ba8ab9b7f7f7a9"})
		b.SetResolver("003_trigrams.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "fae9fb06ac5b01da0ffb2aff58b7a578"})
		}()

	return nil
}()
