// Package data contains the types for schema 'public'.
package data

// Code generated by xo. DO NOT EDIT.

// Country represents a row from 'public.countries'.
type Country struct {
	ID           int    `db:"id"`            // id
	ReadableName string `db:"readable_name"` // readable_name
}
