// Package data contains the types for schema 'public'.
package data

// Code generated by xo. DO NOT EDIT.

// Customer represents a row from 'public.customers'.
type Customer struct {
	ID int `db:"id"` // id
}
