// Package data contains the types for schema 'public'.
package data

// Code generated by xo. DO NOT EDIT.

// Good represents a row from 'public.goods'.
type Good struct {
	ID          int     `db:"id"`          // id
	Code        string  `db:"code"`        // code
	Description string  `db:"description"` // description
	Price       float64 `db:"price"`       // price
	Amount      int16   `db:"amount"`      // amount
}
