// Package data contains the types for schema 'public'.
package data

import "time"

// Code generated by xo. DO NOT EDIT.

// Invoice represents a row from 'public.invoices'.
type Invoice struct {
	ID                   int64     `db:"id"`                     // id
	CustomerID           int       `db:"customer_id"`            // customer_id
	DestinationCountryID int       `db:"destination_country_id"` // destination_country_id
	InvoiceDate          time.Time `db:"invoice_date"`           // invoice_date
}
