// Package data contains the types for schema 'public'.
package data

// Code generated by xo. DO NOT EDIT.

// InvoicePart represents a row from 'public.invoice_parts'.
type InvoicePart struct {
	ID        int64   `db:"id"`         // id
	GoodID    int     `db:"good_id"`    // good_id
	UnitPrice float64 `db:"unit_price"` // unit_price
	Quantity  int     `db:"quantity"`   // quantity
	InvoiceID int64   `db:"invoice_id"` // invoice_id
}
