// Package data contains the types for schema 'public'.
package data

// Code generated by xo. DO NOT EDIT.

// User represents a row from 'public.users'.
type User struct {
	ID          int    `db:"id"`           // id
	Name        string `db:"name"`         // name
	Password    string `db:"password"`     // password
	AccountType int    `db:"account_type"` // account_type
	Login       string `db:"login"`        // login
}
