version: '3'

services:
  router:
    # The official v2.0 Traefik docker image
    image: traefik:v2.0
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=inter-net"
      - "--entrypoints.web.address=:80"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - inter-net
    labels:
      - "traefik.http.middlewares.testheader.headers.accesscontrolallowmethods=GET,OPTIONS,PUT"
      - "traefik.http.middlewares.testheader.headers.accesscontrolalloworigin=*"
      - "traefik.http.middlewares.testheader.headers.addvaryheader=true"

  shop-db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - shop-data:/var/lib/postgresql/data
    networks:
      - inter-net
    environment:
      POSTGRES_DB: shop
      POSTGRES_PASSWORD:

  trash-db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - inter-net
    ports:
      - "27017:27017"
    volumes:
      - trash-data:/data/db
      - mongo-config:/data/configdb

  server:
    image: shop-server:latest
    build:
      dockerfile: ./shop-server/Dockerfile
      context: .
    networks:
      - inter-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`api.localhost`)"
      - "traefik.http.routers.server.entrypoints=web"
      - "traefik.http.services.server-service.loadbalancer.server.port=80"

  frontend:
    image: node
    working_dir: /client
    command: npm run serve
    networks:
      - inter-net
    volumes:
    - ./client:/client
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend-service.loadbalancer.server.port=8080"

networks:
  inter-net:

volumes:
  shop-data:
  trash-data:
  mongo-config: