version: '3'

services:
  shop-db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - shop-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: shop
      POSTGRES_PASSWORD:

  trash-db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - trash-data:/data/db
      - mongo-config:/data/configdb

volumes:
  shop-data:
  trash-data:
  mongo-config: