version: '3'

services:
  cars-db:
    volumes:
      - ./used-cars-data:/var/lib/postgresql/data
    image: postgres:alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: used-cars
      POSTGRES_PASSWORD: password
