version: '3'

services:
  cassandra-db:
    image: cassandra
    networks:
      - inter-net
    volumes:
      - cassandra-v:/var/lib/cassandra
    ports:
      - "9088:9042"

networks:
  inter-net:

volumes:
  cassandra-v: